version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb'
    restart: always
    ports:
      - 3306:3306
    volumes:
      - './mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_ROOT_PASSWORD=123456
